parameters:
    upload.class: Sphax\SpriteHmiBundle\Services\UploadService
    yaml.class: Sphax\SpriteHmiBundle\YamlParser\YamlParser

services:
    twig.extension.image_operation:
        class: Sphax\SpriteHmiBundle\Twig\Extension\ImageOperation
        tags:
            - { name: twig.extension }
        arguments: [@kernel]

    twig.extension.get_sprite_conf:
        class: Sphax\SpriteHmiBundle\Twig\Extension\GetSpriteConf
        tags:
            - { name: twig.extension }
        arguments: [@service_container]

    upload:
        class: %upload.class%
    yaml.parser:
        class: %yaml.class%